-----------------------------------
-- Abyssea pops LSB left commented out (Vunkerl, Misareaux, Uleguerand): retail requirements. Not a module.
-- GENERATED by tools/custom/gen_abyssea_pops.py (BG Wiki zone NM tables). Do not edit by hand: rerun and diff.
-- [zone] = { [??? script name] = { mob = id (nearest spawn of its NM), items = { trade } or kis = { key items } } }
-----------------------------------
local data =
{
    [xi.zone.ABYSSEA_MISAREAUX] =
    {
        qm1   = { mob = 17662464, items = { 3085 } }, -- Minax_Bugard: bewitching_tusk
        qm2   = { mob = 17662465, items = { 3086 } }, -- Sirrush: handful_of_molt_scraps
        qm3   = { mob = 17662466, items = { 3087 } }, -- Funereal_Apkallu: handful_of_apkallu_down
        qm4   = { mob = 17662467, items = { 3088 } }, -- Manohra: avian_remex
        qm5   = { mob = 17662468, items = { 3089 } }, -- Cep-Kamuy: chunk_of_orobon_cheekmeat
        qm6   = { mob = 17662469, items = { 3090 } }, -- Ironclad_Observer: spheroid_plate
        qm7   = { mob = 17662470, items = { 3091 } }, -- Nehebkau: hardened_raptor_skin
        qm8   = { mob = 17662471, items = { 3092 } }, -- Avalerion: mocking_beak
        qm9   = { mob = 17662472, items = { 3093, 3094 } }, -- Karkatakam: slice_of_high-quality_crab_meat, chunk_of_high-quality_rock_salt
        qm10  = { mob = 17662473, items = { 3095 } }, -- Nonno: worm-eaten_bud
        qm11  = { mob = 17662474, items = { 3096 } }, -- Tuskertrap: spotted_flyfrond
        qm12  = { mob = 17662475, items = { 3097 } }, -- Npfundlwa: black_rabbit_tail
        qm13  = { mob = 17662476, kis = { xi.keyItem.GLISTENING_OROBON_LIVER, xi.keyItem.DOFFED_POROGGO_HAT } }, -- Cirein-croin: key items
        qm14  = { mob = 17662477, kis = { xi.keyItem.JAGGED_APKALLU_BEAK, xi.keyItem.CLIPPED_BIRD_WING, xi.keyItem.BLOODIED_BAT_FUR } }, -- Amhuluk: key items
        qm15  = { mob = 17662478, kis = { xi.keyItem.BLOODSTAINED_BUGARD_FANG, xi.keyItem.GNARLED_LIZARD_NAIL, xi.keyItem.MOLTED_PEISTE_SKIN } }, -- Sobek: key items
        qm16  = { mob = 17662479, kis = { xi.keyItem.SCALDING_IRONCLAD_SPIKE, xi.keyItem.BLAZING_CLUSTER_SOUL } }, -- Ironclad_Pulverizer: key items
        qm17  = { mob = 17662481, kis = { xi.keyItem.GLISTENING_OROBON_LIVER, xi.keyItem.DOFFED_POROGGO_HAT } }, -- Cirein-croin: key items
        qm18  = { mob = 17662482, kis = { xi.keyItem.JAGGED_APKALLU_BEAK, xi.keyItem.CLIPPED_BIRD_WING, xi.keyItem.BLOODIED_BAT_FUR } }, -- Amhuluk: key items
        qm19  = { mob = 17662483, kis = { xi.keyItem.BLOODSTAINED_BUGARD_FANG, xi.keyItem.GNARLED_LIZARD_NAIL, xi.keyItem.MOLTED_PEISTE_SKIN } }, -- Sobek: key items
        qm20  = { mob = 17662484, kis = { xi.keyItem.SCALDING_IRONCLAD_SPIKE, xi.keyItem.BLAZING_CLUSTER_SOUL } }, -- Ironclad_Pulverizer: key items
        qm21  = { mob = 17662486, kis = { xi.keyItem.GLISTENING_OROBON_LIVER, xi.keyItem.DOFFED_POROGGO_HAT } }, -- Cirein-croin: key items
        qm22  = { mob = 17662487, kis = { xi.keyItem.JAGGED_APKALLU_BEAK, xi.keyItem.CLIPPED_BIRD_WING, xi.keyItem.BLOODIED_BAT_FUR } }, -- Amhuluk: key items
        qm23  = { mob = 17662488, kis = { xi.keyItem.BLOODSTAINED_BUGARD_FANG, xi.keyItem.GNARLED_LIZARD_NAIL, xi.keyItem.MOLTED_PEISTE_SKIN } }, -- Sobek: key items
        qm24  = { mob = 17662489, kis = { xi.keyItem.SCALDING_IRONCLAD_SPIKE, xi.keyItem.BLAZING_CLUSTER_SOUL } }, -- Ironclad_Pulverizer: key items
    },
    [xi.zone.ABYSSEA_ULEGUERAND] =
    {
        qm1   = { mob = 17813925, items = { 3245, 3251 } }, -- Ironclad_Triturator: bevel_gear, vial_of_gear_fluid
        qm2   = { mob = 17813927, items = { 3246, 3247, 3253 } }, -- Dhorme_Khimaira: snow_god_core, sisyphus_fragment, high-quality_marid_hide
        qm3   = { mob = 17813930, items = { 3257, 3248 } }, -- Blanga: benumbed_eye, rimed_wing
        qm4   = { mob = 17813931, items = { 3249, 3259 } }, -- Yaguarogui: audumbla_hide, high-quality_black_tiger_hide
        qm5   = { mob = 17813933, items = { 3250 } }, -- Koghatu: helical_gear
        qm6   = { mob = 17813935, items = { 3252 } }, -- Upas-Kamuy: gelid_arm
        qm7   = { mob = 17813937, items = { 3254 } }, -- Veri_Selen: ice_wyvern_scale
        qm8   = { mob = 17813938, items = { 3255 } }, -- Anemic_Aloysius: handful_of_whiteworm_clay
        qm9   = { mob = 17813939, items = { 3256 } }, -- Chillwing_Hwitti: imp_sentrys_horn
        qm10  = { mob = 17813940, items = { 3258 } }, -- Audumbla: high-quality_buffalo_horn
        qm11  = { mob = 17813910, kis = { xi.keyItem.WARPED_IRON_GIANT_NAIL, xi.keyItem.DENTED_CHARIOT_SHIELD } }, -- Pantokrator: key items
        qm12  = { mob = 17813911, kis = { xi.keyItem.TORN_KHIMAIRA_WING } }, -- Apademak: key items
        qm13  = { mob = 17813912, kis = { xi.keyItem.BEGRIMED_DRAGON_HIDE } }, -- Isgebind: key items
        qm14  = { mob = 17813913, kis = { xi.keyItem.DECAYING_DIREMITE_FANG } }, -- Resheph: key items
        qm15  = { mob = 17813914, kis = { xi.keyItem.WARPED_IRON_GIANT_NAIL, xi.keyItem.DENTED_CHARIOT_SHIELD } }, -- Pantokrator: key items
        qm16  = { mob = 17813915, kis = { xi.keyItem.TORN_KHIMAIRA_WING } }, -- Apademak: key items
        qm17  = { mob = 17813916, kis = { xi.keyItem.BEGRIMED_DRAGON_HIDE } }, -- Isgebind: key items
        qm18  = { mob = 17813917, kis = { xi.keyItem.DECAYING_DIREMITE_FANG } }, -- Resheph: key items
        qm19  = { mob = 17813918, kis = { xi.keyItem.WARPED_IRON_GIANT_NAIL, xi.keyItem.DENTED_CHARIOT_SHIELD } }, -- Pantokrator: key items
        qm20  = { mob = 17813919, kis = { xi.keyItem.TORN_KHIMAIRA_WING } }, -- Apademak: key items
        qm21  = { mob = 17813920, kis = { xi.keyItem.BEGRIMED_DRAGON_HIDE } }, -- Isgebind: key items
        qm22  = { mob = 17813921, kis = { xi.keyItem.DECAYING_DIREMITE_FANG } }, -- Resheph: key items
    },
    [xi.zone.ABYSSEA_VUNKERL] =
    {
        qm1   = { mob = 17666487, items = { 3098 } }, -- Khalkotaur: gnarled_taurus_horn
        qm2   = { mob = 17666488, items = { 3099 } }, -- Quasimodo: gargouille_stone
        qm3   = { mob = 17666489, items = { 3100 } }, -- Iku-Turso: moonbeam_clam
        qm4   = { mob = 17666490, items = { 3101 } }, -- Dvalinn: dented_skull
        qm5   = { mob = 17666491, items = { 3102 } }, -- Kadraeth_the_Hatespawn: stiffened_tentacle
        qm6   = { mob = 17666492, items = { 3103 } }, -- Rakshas: black_whisker
        qm7   = { mob = 17666493, items = { 3104 } }, -- Seps: opaque_wing
        qm8   = { mob = 17666494, items = { 3105 } }, -- Xan: fortune_wing
        qm9   = { mob = 17666495, items = { 3106 } }, -- Chhir_Batti: vial_of_djinn_ashes
        qm10  = { mob = 17666496, items = { 3107 } }, -- Armillaria: shockshroom
        qm11  = { mob = 17666497, items = { 3108 } }, -- Pascerpot: crawler_floatstone
        qm12  = { mob = 17666498, items = { 3109 } }, -- Gnawtooth_Gary: high-quality_rabbit_hide
        qm13  = { mob = 17666499, kis = { xi.keyItem.INGROWN_TAURUS_NAIL, xi.keyItem.OSSIFIED_GARGOUILLE_HAND, xi.keyItem.IMBRUED_VAMPYR_FANG } }, -- Bukhis: key items
        qm14  = { mob = 17666500, kis = { xi.keyItem.GLOSSY_SEA_MONK_SUCKER, xi.keyItem.SHIMMERING_PUGIL_SCALE } }, -- Sedna: key items
        qm15  = { mob = 17666501, kis = { xi.keyItem.DECAYED_DVERGR_TOOTH, xi.keyItem.PULSATING_SOULFLAYER_BEARD, xi.keyItem.CHIPPED_IMPS_OLIFANT } }, -- Durinn: key items
        qm16  = { mob = 17666502, kis = { xi.keyItem.WARPED_SMILODON_CHOKER, xi.keyItem.MALODOROUS_MARID_FUR } }, -- Karkadann: key items
        qm17  = { mob = 17666503, kis = { xi.keyItem.INGROWN_TAURUS_NAIL, xi.keyItem.OSSIFIED_GARGOUILLE_HAND, xi.keyItem.IMBRUED_VAMPYR_FANG } }, -- Bukhis: key items
        qm18  = { mob = 17666504, kis = { xi.keyItem.GLOSSY_SEA_MONK_SUCKER, xi.keyItem.SHIMMERING_PUGIL_SCALE } }, -- Sedna: key items
        qm19  = { mob = 17666505, kis = { xi.keyItem.DECAYED_DVERGR_TOOTH, xi.keyItem.PULSATING_SOULFLAYER_BEARD, xi.keyItem.CHIPPED_IMPS_OLIFANT } }, -- Durinn: key items
        qm20  = { mob = 17666506, kis = { xi.keyItem.WARPED_SMILODON_CHOKER, xi.keyItem.MALODOROUS_MARID_FUR } }, -- Karkadann: key items
        qm21  = { mob = 17666507, kis = { xi.keyItem.INGROWN_TAURUS_NAIL, xi.keyItem.OSSIFIED_GARGOUILLE_HAND, xi.keyItem.IMBRUED_VAMPYR_FANG } }, -- Bukhis: key items
        qm22  = { mob = 17666508, kis = { xi.keyItem.GLOSSY_SEA_MONK_SUCKER, xi.keyItem.SHIMMERING_PUGIL_SCALE } }, -- Sedna: key items
        qm23  = { mob = 17666509, kis = { xi.keyItem.DECAYED_DVERGR_TOOTH, xi.keyItem.PULSATING_SOULFLAYER_BEARD, xi.keyItem.CHIPPED_IMPS_OLIFANT } }, -- Durinn: key items
        qm24  = { mob = 17666510, kis = { xi.keyItem.WARPED_SMILODON_CHOKER, xi.keyItem.MALODOROUS_MARID_FUR } }, -- Karkadann: key items
    },
}

return data
