#!/usr/bin/env python3
"""Generate modules/custom/lua/gotoexp_data.lua: the EXP camps !gotoexp can send players to.
Usage: ~/lsb-venv/bin/python3 tools/custom/gen_gotoexp_data.py   (after tools/custom/gen_hunt_data.py)
Reads modules/custom/lua/hunt_data.lua (open-world zones, monster families, their usual levels and spawn counts; that
generator already leaves out cities, instanced / Dynamis zones and special-access content) and each zone's
data/zones/<zone>/npcs.yaml for a safe landing spot: its Home Point (#1 first), else its Survival Guide. Zones with
neither are left out. Changes nothing else. Background: docs/custom/NOTES.md (!gotoexp).
"""
import os
import re
import yaml

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
HUNT = os.path.join(REPO, 'modules', 'custom', 'lua', 'hunt_data.lua')
ZONES = os.path.join(REPO, 'data', 'zones')
OUT = os.path.join(REPO, 'modules', 'custom', 'lua', 'gotoexp_data.lua')

zoneIds = dict((k.lower(), int(v)) for k, v in re.findall(r'^\s+([A-Z0-9_]+)\s*=\s*(\d+),', open(os.path.join(REPO, 'scripts', 'enum', 'zone.codegen.lua')).read(), re.M))
zoneKeys = {v: k for k, v in zoneIds.items()}

# kills lines: { zone = N, family = F, name = '...', zoneName = '...', low = L, high = H }, -- C spawns
pattern = re.compile(r"\{ zone = +(\d+), family = +(\d+), name = '([^']*)', zoneName = '((?:[^'\\]|\\.)*)', low = (\d+), high = (\d+) \}, -- (\d+) spawns")
zones = {}
inKills = False
for line in open(HUNT):
    if line.startswith('data.kills'):
        inKills = True
    elif line.startswith('data.nms'):
        inKills = False
    m = pattern.search(line) if inKills else None
    if m:
        zone = int(m.group(1))
        z = zones.setdefault(zone, {'name': m.group(4), 'families': []})
        z['families'].append((m.group(3), int(m.group(5)), int(m.group(6)), int(m.group(7))))


def landing(zoneKey):
    path = os.path.join(ZONES, zoneKey, 'npcs.yaml')
    if not os.path.exists(path):
        return None
    npcs = (yaml.safe_load(open(path)) or {}).get('npcs') or {}
    homes, guides = [], []
    for npc in npcs.values():
        script = str(npc.get('script', ''))
        at = npc.get('at')
        if not at or len(at) < 3:
            continue
        m = re.match(r'^Home_?Point_?#(\d+)$', script)
        if m:
            homes.append((int(m.group(1)), at, 'Home Point #' + m.group(1)))
        elif script == 'Survival_Guide':
            guides.append((0, at, 'Survival Guide'))
    for choice in (sorted(homes, key=lambda h: h[0]) + guides)[:1]:
        at = choice[1]
        rot = at[3] if len(at) > 3 else 0
        return (at[0], at[1], at[2], rot, choice[2])
    return None


lines = ['-----------------------------------',
         '-- !gotoexp: EXP camps. Not a module (loaded by require).',
         '-- GENERATED by tools/custom/gen_gotoexp_data.py from hunt_data.lua and data/zones/*/npcs.yaml. Do not edit by',
         '-- hand: rerun and diff. [zone id] = { name, landing = { x, y, z, rot, label }, families = { { name, low, high,',
         '-- spawns } } }; landing is the zone\'s Home Point (#1 first) or Survival Guide.',
         '-----------------------------------',
         'local data = {}',
         '',
         'data.zones =',
         '{']
kept, dropped = 0, []
for zone in sorted(zones):
    key = zoneKeys.get(zone)
    spot = landing(key) if key else None
    if not spot:
        dropped.append(zones[zone]['name'])
        continue
    kept += 1
    z = zones[zone]
    fams = ', '.join(f"{{ '{n}', {lo}, {hi}, {c} }}" for n, lo, hi, c in sorted(z['families'], key=lambda f: f[1]))
    lines.append(f"    [{zone}] = {{ name = '{z['name']}', landing = {{ {spot[0]}, {spot[1]}, {spot[2]}, {spot[3]}, '{spot[4]}' }}, families = {{ {fams} }} }},")
lines += ['}', '', 'return data', '']
open(OUT, 'w').write('\n'.join(lines))
print(f'{kept} zones with a landing spot -> {os.path.relpath(OUT, REPO)}; {len(dropped)} without: {", ".join(dropped)}')
