#!/usr/bin/env python3
"""Generate modules/custom/lua/hunt_data.lua: the targets the daily hunts can give.

Usage: ~/lsb-venv/bin/python3 tools/custom/gen_hunt_data.py
Reads data/zones/*/mobs.yaml, zone.yaml and data/ecosystems.yaml; changes nothing else. Diff the result before committing.
Background: docs/custom/NOTES.md (Daily hunts).

Kill hunts: one monster family in one zone ("kill 12 Goblins in Batallia Downs"), from monsters that spawn on their own
(no battlefield / fished / event / called / scripted / lottery spawns, not notorious) with at least MIN_SPAWNS of them.
NM hunts: notorious monsters that spawn on their own or from a placeholder (lottery), not scripted pops.
Left out: cities, instanced and Dynamis zones, and content that needs special access (Abyssea, Limbus, Escha / Reisenjima,
Sky / Sea, the [U] zones), listed in SKIP.
"""

import os
import re
import sys

import yaml

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
ZONES = os.path.join(REPO, 'data', 'zones')
OUT = os.path.join(REPO, 'modules', 'custom', 'lua', 'hunt_data.lua')

MIN_SPAWNS = 4
BAD_MOB_TYPES = {'battlefield', 'fished', 'event', 'called', 'notorious'}
SKIP = re.compile(r'^(abyssea_|escha_|reisenjima|temenos|apollyon|ruaun_gardens|altaieu|grand_palace_of_huxzoi|'
                  r'the_garden_of_ruhmet|empyreal_paradox|walk_of_echoes|.*_u$|.*_p$|nyzul_isle|.*_remnants|'
                  r'mog_garden|gm_home|.*_airship|.*_ferry|residential_area|lower_delkfutts_tower_hi)')

# species -> (family id, family key) from the ecosystems file
species = {}
for eco in yaml.safe_load(open(os.path.join(REPO, 'data', 'ecosystems.yaml')))['ecosystems'].values():
    for famKey, fam in (eco.get('families') or {}).items():
        for spKey in (fam.get('species') or {}):
            species[spKey] = (fam['id'], famKey)

zoneIds = dict((k.lower(), int(v)) for k, v in re.findall(r'^\s+([A-Z0-9_]+)\s*=\s*(\d+),', open(os.path.join(REPO, 'scripts', 'enum', 'zone.codegen.lua')).read(), re.M))


def title(key):
    return ' '.join(w.capitalize() if w not in ('of', 'the', 'de') else w for w in key.split('_')).replace(' S', ' [S]') if not key.endswith('_s') else title(key[:-2]) + ' [S]'


def as_list(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


kills, nms = [], []

for zone in sorted(os.listdir(ZONES)):
    mobsPath = os.path.join(ZONES, zone, 'mobs.yaml')
    zonePath = os.path.join(ZONES, zone, 'zone.yaml')
    if not os.path.exists(mobsPath) or not os.path.exists(zonePath) or SKIP.match(zone) or zone not in zoneIds:
        continue

    zoneTypes = set(as_list((yaml.safe_load(open(zonePath)) or {}).get('type')))
    if zoneTypes & {'city', 'instanced', 'dynamis'}:
        continue

    data = yaml.safe_load(open(mobsPath)) or {}
    templates = data.get('templates') or {}
    groups = {}  # family id -> {levels, count, familyKey}

    for mobId, spawn in (data.get('spawns') or {}).items():
        tpl = templates.get(spawn.get('template'))
        level = as_list(spawn.get('level'))
        if not tpl or len(level) != 2 or tpl.get('species') not in species:
            continue

        mobTypes = set(as_list(tpl.get('type')))
        spawnTypes = set(as_list(((tpl.get('attributes') or {}).get('spawn') or {}).get('type')))

        if 'notorious' in mobTypes:
            if spawnTypes & {'scripted'} or mobTypes & (BAD_MOB_TYPES - {'notorious'}):
                continue
            nms.append((zone, int(mobId), spawn['template'], int(level[0]), int(level[1])))
            continue

        if mobTypes & BAD_MOB_TYPES or spawnTypes & {'scripted', 'lottery'}:
            continue

        famId, famKey = species[tpl['species']]
        if famKey == 'unclassified':
            continue
        g = groups.setdefault(famId, {'levels': [], 'count': 0, 'key': famKey})
        g['levels'].append((int(level[0]), int(level[1])))
        g['count'] += 1

    for famId, g in groups.items():
        if g['count'] < MIN_SPAWNS:
            continue
        lows = sorted(lo for lo, hi in g['levels'])
        # the middle half of the spawns sets the hunt's level, so a few stray high / low ones don't
        low, high = lows[len(lows) // 4], sorted(hi for lo, hi in g['levels'])[(3 * len(lows)) // 4]
        kills.append((zone, famId, g['key'], low, high, g['count']))

# NM names are unique per zone: keep the first spawn of each
seen, nmList = set(), []
for zone, mobId, name, low, high in sorted(nms, key=lambda n: n[1]):
    if (zone, name) not in seen:
        seen.add((zone, name))
        nmList.append((zone, mobId, name, low, high))

lines = ['-----------------------------------',
         '-- Daily hunts: the targets they can give. Not a module (loaded by require).',
         '-- GENERATED by tools/custom/gen_hunt_data.py from data/zones/*/mobs.yaml. Do not edit by hand: rerun and diff.',
         '-- kills: { zone, family, name, zoneName, low, high } = kill monsters of that family in that zone; low / high are',
         '-- the typical levels there. nms: [first mob id] = { zone, name, zoneName, low, high }.',
         '-----------------------------------',
         'local data = {}',
         '',
         'data.kills =',
         '{']
for zone, famId, famKey, low, high, count in sorted(kills, key=lambda k: (k[3], k[0])):
    lines.append(f"    {{ zone = {zoneIds[zone]:3}, family = {famId:3}, name = '{title(famKey)}', zoneName = '{title(zone)}', low = {low}, high = {high} }}, -- {count} spawns")
lines += ['}', '', 'data.nms =', '{']
for zone, mobId, name, low, high in sorted(nmList, key=lambda n: (n[3], n[1])):
    display = name.replace('_', ' ').replace("'", "\\'")
    lines.append(f"    [{mobId}] = {{ zone = {zoneIds[zone]:3}, name = '{name}', display = '{display}', zoneName = '{title(zone)}', low = {low}, high = {high} }},")
lines += ['}', '', 'return data', '']
open(OUT, 'w').write('\n'.join(lines))
print(f'{len(kills)} kill hunts, {len(nmList)} NM hunts -> {os.path.relpath(OUT, REPO)}')
